name: cryptology
description: A cryptography library for use pointycastle in dart and flutter.
version: 0.0.5
homepage: https://mohrazium.github.io/cryptology/



environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
